server:
  port: 8088
spring:
  application:
    name: blog
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/blog?character=utf8
      driver: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.mapper
  type-aliases-package: io.github.yu.model