server:
  port: 8088
spring:
  application:
    name: blog
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
mybatis:
  mapper-locations: classpath*:mapper/*.xml
blog:
  password:
    key: springbootyublog
ip:
  key: VVKBZ-KRVK4-XY7UB-D32WU-4YZO2-NCFJ3